#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
set -eu
set -o pipefail
LC_ALL=C
if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
	exit 1
fi
trap "rm -f /run/$(basename $0).pid; exit" INT TERM EXIT
echo "$BASHPID" > /run/$(basename $0).pid
quien=$(who | cut -d' ' -f1 | sort | uniq)

function iptables_clean () {
	if [[ -f /root/.listo ]]; then
		echo -e "\e[00;31mERROR: easypxe ya se ha ejecutado en este pc.\e[00m"
		exit 1
	fi
	iptables-save >> /home/"$quien"/iptables.save
	iptables -F
	iptables -X
	iptables -Z
	iptables -t nat -F
	iptables -t nat -X
	iptables -t mangle -F
	iptables -t mangle -X
	iptables -P INPUT ACCEPT
	iptables -P FORWARD ACCEPT
	iptables -P OUTPUT ACCEPT
}

function primeros () {
	apt-get -q update
	apt-get -y install dnsmasq nfs-kernel-server tftpd-hpa
	mkdir -p /var/lib/tftpboot
	mkdir -p /opt/nfs
	echo "dhcp-range=192.168.1.200,192.168.1.250,12h" >> /etc/dnsmasq.conf
	echo "dhcp-no-override" >> /etc/dnsmasq.conf
	echo "enable-tftp" >> /etc/dnsmasq.conf
	echo "tftp-root=/var/lib/tftpboot" >> /etc/dnsmasq.conf
	echo "/opt/nfs	*(rw,no_root_squash,async,no_subtree_check)" >> /etc/exports
	exportfs -a
}

function limpieza () {
	history -c
	apt-get clean
	rm -rf /root/.local/share/Trash/*
	rm -rf /home/*/.local/share/Trash/*
	rm -rf /home/*/.cache/*
	rm -rf /tmp/*
	rm -rf /var/tmp/*
	echo -e "\e[00;1;92mFinalizado...\e[00m"
	touch /root/.listo
}

case "$1" in
	debian)
		iptables_clean
		primeros
		echo "dhcp-boot=pxelinux.0" >> /etc/dnsmasq.conf
		systemctl restart dnsmasq.service
		wget -O - http://httpredir.debian.org/debian/dists/jessie/main/installer-i386/current/images/netboot/netboot.tar.gz > /var/lib/tftpboot/netboot.tar.gz
		cd /var/lib/tftpboot/
		tar -xzf netboot.tar.gz
		rm -f /var/lib/tftpboot/netboot.tar.gz
		limpieza
		;;

	ubuntu)
		iptables_clean
		primeros
		echo "dhcp-boot=pxelinux.0,root,192.168.1.1" >> /etc/dnsmasq.conf
		systemctl restart dnsmasq.service
		wget -O - http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/installer-i386/current/images/netboot/netboot.tar.gz > /var/lib/tftpboot/netboot.tar.gz
		cd /var/lib/tftpboot/
		tar -xzf netboot.tar.gz
		rm -f /var/lib/tftpboot/netboot.tar.gz
		limpieza
		;;

	mint)
		iptables_clean
		primeros
		systemctl restart dnsmasq.service
		limpieza
		;;

	*)
		echo "USO: $(basename $0) {debian|ubuntu|mint}"
		;;

esac

rm -f /run/$(basename $0).pid
trap - INT TERM EXIT
exit 0

=================================

#!/bin/bash
if [[ $USER != root ]]; then
echo "Error: Debe tener privilegios de ROOT"
exit 0
fi
cd ~
apt-get -y install isc-dhcp-server tftpd-hpa tftp-hpa xinetd apache2
echo -e 'ddns-update-style none;'"\n"'allow booting;'"\n"'allow bootp;'"\n"'default-lease-time 600;'"\n"'max-lease-time 7200;'"\n"'log-facility local7;'"\n"'# labidiomas'"\n"'subnet 10.0.0.0 netmask 255.255.255.0 {'"\n"'	allow unknown-clients;'"\n"'	range dynamic-bootp 10.0.0.10 10.0.0.100;'"\n"'	filename "pxelinux.0";'"\n"'	option broadcast-address 10.0.0.255;'"\n"'	option routers 10.0.0.1;'"\n"'	}' > /etc/dhcp/dhcpd.conf
service isc-dhcp-server restart
echo -e '# /etc/default/tftpd-hpa'"\n"'TFTP_USERNAME="tftp"'"\n"'TFTP_DIRECTORY="/var/lib/tftpboot"'"\n"'RUN_DAEMON="yes"' > /etc/default/tftpd-hpa
service tftpd-hpa restart
echo -e "service tftp""\n""  {""\n""        disable                 = no""\n""        socket_type             = dgram""\n""        wait                    = yes""\n""        user                    = root""\n""        server                  = /usr/sbin/in.tftpd""\n""        server_args             = -v -s /var/lib/tftpboot""\n""        only_from   = 10.0.0.1/24""\n""        interface   = 10.0.0.1""\n""  }" > /etc/xinetd.d/tftp
killall -HUP xinetd
wget http://archive.ubuntu.com/ubuntu/dists/precise-updates/main/installer-amd64/current/images/raring-netboot/netboot.tar.gz
tar -xvzf netboot.tar.gz -C /var/lib/tftpboot/
echo -e "tmpfs /tmp tmpfs noatime,nodev 0 0" >> /etc/fstab
mkdir -p /var/lib/tftpboot/ubuntu
chown -R tftp:tftp /var/lib/tftpboot
cd /var/www
ln -s /var/lib/tftpboot/ubuntu/
service apache2 restart
cd /etc/init.d
echo -e "#! /bin/sh""\n""### BEGIN INIT INFO""\n""# Provides:          PXE""\n""# Required-Start:""\n""# Required-Stop:""\n""# Default-Start:     2 3 4 5""\n""# Default-Stop:""\n""# Short-Description: PXE""\n""### END INIT INFO""\n""cp /home/usuario/ubuntu.iso /tmp""\n""mount -o loop /tmp/ubuntu.iso /var/lib/tftpboot/ubuntu""\n""service ssh stop""\n""exit 0" > /etc/init.d/pxe-run
chmod -v +x /etc/init.d/pxe-run
update-rc.d pxe-run start 96 2 3 4 5 .
cd ~
echo finalizado
exit 0
