#!/usr/bin/env bash
# made by sinfallas <sinfallas@yahoo.com>
# licence: gpl-2
LC_ALL=C
if [[ "$EUID" != "0" ]]; then
	echo "error: debes ser root"
	exit 1
fi

if [[ -f /root/.listo ]]; then
	echo "error: easypxe ya se ha ejecutado en este pc"
	exit 1
fi

trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid

debian1="/var/lib/tftpboot/debian/jessie"
debian2="/var/lib/tftpboot/debian"
debian3="/opt/nfs/debian/jessie/i386"
debian4="/opt/nfs/debian/jessie/amd64"

ubuntu1="/var/lib/tftpboot/ubuntu/14.04"
ubuntu2="/var/lib/tftpboot/ubuntu"
ubuntu3="/opt/nfs/ubuntu/14.04/i386"
ubuntu4="/opt/nfs/ubuntu/14.04/amd64"

fedora1="/var/lib/tftpboot/fedora/23"
fedora2="/var/lib/tftpboot/fedora"
fedora3="/opt/nfs/fedora/23/i386"
fedora4="/opt/nfs/fedora/23/amd64"

xanadu1="/var/lib/tftpboot/xanadu/0.9.0"
xanadu2="/var/lib/tftpboot/xanadu"
xanadu3="/opt/nfs/xanadu/0.9.0/i386"
xanadu4="/opt/nfs/xanadu/0.9.0/amd64"

pxe="/var/lib/tftpboot/pxelinux.cfg"
loop="/mnt/loop"

function iptables_clean () {
	iptables-save >> "$HOME"/iptables.save
	iptables -F
	iptables -X
	iptables -Z
	iptables -t nat -F
	iptables -t nat -X
	iptables -t mangle -F
	iptables -t mangle -X
	iptables -P INPUT ACCEPT
	iptables -P FORWARD ACCEPT
	iptables -P OUTPUT ACCEPT
}

function directorios () {
	mkdir -p $loop
	mkdir -p "$HOME"/isos
	mkdir -p $pxe

	mkdir -p $debian1
	mkdir -p $debian2
	mkdir -p $debian3
	mkdir -p $debian4

	mkdir -p $ubuntu1
	mkdir -p $ubuntu2
	mkdir -p $ubuntu3
	mkdir -p $ubuntu4

	mkdir -p $fedora1
	mkdir -p $fedora2
	mkdir -p $fedora3
	mkdir -p $fedora4

	mkdir -p $xanadu1
	mkdir -p $xanadu2
	mkdir -p $xanadu3
	mkdir -p $xanadu4
}

function instalar () {
	if ! [[ -f /root/.instalar ]]; then
		ver=$(lsb_release -c | awk '{print $2}')
		cp /etc/apt/sources.list /etc/apt/sources.list.old
		echo "deb http://archive.ubuntu.com/ubuntu/ $ver main restricted universe multiverse" > /etc/apt/sources.list
		echo "deb http://security.ubuntu.com/ubuntu/ $ver-security main restricted universe multiverse" >> /etc/apt/sources.list
		echo "deb http://archive.ubuntu.com/ubuntu/ $ver-updates main restricted universe multiverse" >> /etc/apt/sources.list
		apt-get -q update
		apt-get -y install dnsmasq nfs-kernel-server tftpd-hpa syslinux
		apt-get clean
		mv -f /etc/apt/sources.list.old /etc/apt/sources.list
		touch /root/.instalar
	fi
}

function primeros () {
	if ! [[ -f /root/.primeros ]]; then
		echo "dhcp-range=192.168.1.200,192.168.1.250,12h" >> /etc/dnsmasq.conf
		echo "dhcp-boot=pxelinux.0,root,192.168.1.1" >> /etc/dnsmasq.conf
		echo "dhcp-no-override" >> /etc/dnsmasq.conf
		echo "enable-tftp" >> /etc/dnsmasq.conf
		echo "tftp-root=/var/lib/tftpboot" >> /etc/dnsmasq.conf
		systemctl restart dnsmasq.service
		echo "/opt/nfs	*(rw,no_root_squash,async,no_subtree_check)" > /etc/exports
		exportfs -a
		cp /usr/lib/syslinux/pxelinux.0 /var/lib/tftpboot
		cp /usr/lib/syslinux/vesamenu.c32 /var/lib/tftpboot/
		cp "$HOME"/isos/xanadu-grub.png $pxe/logo.png
		touch /root/.primeros
	fi
}

function limpieza () {
	history -c
	rm -rf /root/.local/share/trash/*
	rm -rf /home/*/.local/share/trash/*
	rm -rf /home/*/.cache/*
	rm -rf /tmp/*
	rm -rf /var/tmp/*
	rm -rf /var/lib/tftpboot/*
	rm -rf /opt/nfs/*
}

function menu () {
	echo "default vesamenu.c32" > $pxe/default
	echo "timeout 600" >> $pxe/default
	echo "ontimeout bootlocal" >> $pxe/default
	echo "prompt 0" >> $pxe/default
	echo "menu include pxelinux.cfg/pxe.conf" >> $pxe/default
	echo "noescape 1" >> $pxe/default
	echo "label bootlocal" >> $pxe/default
	echo "	localboot 0" >> $pxe/default
	echo "	text help" >> $pxe/default
	echo "	boot to local hard disk" >> $pxe/default
	echo "	endtext" >> $pxe/default
	echo "menu begin ubuntu" >> $pxe/default
	echo "menu title ubuntu" >> $pxe/default
	echo "	label previous" >> $pxe/default
	echo "	menu label previous menu" >> $pxe/default
	echo "	text help" >> $pxe/default
	echo "	return to previous menu" >> $pxe/default
	echo "	endtext" >> $pxe/default
	echo "	menu exit" >> $pxe/default
	echo "	menu separator" >> $pxe/default
	echo "	menu include ubuntu/ubuntu.menu" >> $pxe/default
	echo "menu end" >> $pxe/default
	echo "menu begin xanadu" >> $pxe/default
	echo "menu title xanadu" >> $pxe/default
	echo "	label previous" >> $pxe/default
	echo "	menu label previous menu" >> $pxe/default
	echo "	text help" >> $pxe/default
	echo "	return to previous menu" >> $pxe/default
	echo "	endtext" >> $pxe/default
	echo "	menu exit" >> $pxe/default
	echo "	menu separator" >> $pxe/default
	echo "	menu include xanadu/xanadu.menu" >> $pxe/default
	echo "menu end" >> $pxe/default
	echo "menu begin fedora" >> $pxe/default
	echo "menu title fedora" >> $pxe/default
	echo "	label previous" >> $pxe/default
	echo "	menu label previous menu" >> $pxe/default
	echo "	text help" >> $pxe/default
	echo "	return to previous menu" >> $pxe/default
	echo "	endtext" >> $pxe/default
	echo "	menu exit" >> $pxe/default
	echo "	menu separator" >> $pxe/default
	echo "	menu include fedora/fedora.menu" >> $pxe/default
	echo "menu end" >> $pxe/default
	echo "menu end" >> $pxe/default
	echo "menu begin debian" >> $pxe/default
	echo "menu title debian" >> $pxe/default
	echo "	label previous" >> $pxe/default
	echo "	menu label previous menu" >> $pxe/default
	echo "	text help" >> $pxe/default
	echo "	return to previous menu" >> $pxe/default
	echo "	endtext" >> $pxe/default
	echo "	menu exit" >> $pxe/default
	echo "	menu separator" >> $pxe/default
	echo "	menu include debian/debian.menu" >> $pxe/default
	echo "menu end" >> $pxe/default

	echo "menu title  pxe server" > $pxe/pxe.conf
	echo "menu background pxelinux.cfg/logo.png" >> $pxe/pxe.conf
	echo "noescape 1" >> $pxe/pxe.conf
	echo "allowoptions 1" >> $pxe/pxe.conf
	echo "prompt 0" >> $pxe/pxe.conf
	echo "menu width 80" >> $pxe/pxe.conf
	echo "menu rows 14" >> $pxe/pxe.conf
	echo "menu tabmsgrow 24" >> $pxe/pxe.conf
	echo "menu margin 10" >> $pxe/pxe.conf
	echo "menu color border               30;44      #ffffffff #00000000 std" >> $pxe/pxe.conf

	echo "label 2" > $debian2/debian.menu
	echo "	menu label debian jessie (64-bit)" >> $debian2/debian.menu
	echo "	kernel debian/jessie/amd64/vmlinuz" >> $debian2/debian.menu
	echo "	append boot=netboot=nfs nfsroot=10.10.1.10:/srv/install/debian/jessie/amd64 initrd=debian/jessie/amd64/initrd.lz" >> $debian2/debian.menu
	echo "	text help" >> $debian2/debian.menu
	echo "	boot the debian jessie 64-bit dvd" >> $debian2/debian.menu
	echo "	endtext" >> $debian2/debian.menu
	echo "label 1" >> $debian2/debian.menu
	echo "	menu label debian jessie (32-bit)" >> $debian2/debian.menu
	echo "	kernel debian/jessie/i386/vmlinuz" >> $debian2/debian.menu
	echo "	append boot=netboot=nfs nfsroot=10.10.1.10:/srv/install/debian/jessie/i386 initrd=debian/jessie/i386/initrd.lz" >> $debian2/debian.menu
	echo "	text help" >> $debian2/debian.menu
	echo "	boot the debian jessie 32-bit dvd" >> $debian2/debian.menu
	echo "	endtext" >> $debian2/debian.menu

	echo "label 2" > $ubuntu2/ubuntu.menu
	echo "	menu label ubuntu 14.04 (64-bit)" >> $ubuntu2/ubuntu.menu
	echo "	kernel ubuntu/14.04/amd64/vmlinuz" >> $ubuntu2/ubuntu.menu
	echo "	append boot=casper netboot=nfs nfsroot=10.10.1.10:/srv/install/ubuntu/14.04/amd64 initrd=ubuntu/14.04/amd64/initrd.lz" >> $ubuntu2/ubuntu.menu
	echo "	text help" >> $ubuntu2/ubuntu.menu
	echo "	boot the ubuntu 14.04 64-bit dvd" >> $ubuntu2/ubuntu.menu
	echo "	endtext" >> $ubuntu2/ubuntu.menu
	echo "label 1" >> $ubuntu2/ubuntu.menu
	echo "	menu label ubuntu 14.04 (32-bit)" >> $ubuntu2/ubuntu.menu
	echo "	kernel ubuntu/14.04/i386/vmlinuz" >> $ubuntu2/ubuntu.menu
	echo "	append boot=casper netboot=nfs nfsroot=10.10.1.10:/srv/install/ubuntu/14.04/i386 initrd=ubuntu/14.04/i386/initrd.lz" >> $ubuntu2/ubuntu.menu
	echo "	text help" >> $ubuntu2/ubuntu.menu
	echo "	boot the ubuntu 14.04 32-bit dvd" >> $ubuntu2/ubuntu.menu
	echo "	endtext" >> $ubuntu2/ubuntu.menu

	echo "label 2" > $fedora2/fedora.menu
	echo "	menu label fedora 12 (64-bit)" >> $fedora2/fedora.menu
	echo "	kernel fedora/12/amd64/vmlinuz" >> $fedora2/fedora.menu
	echo "	append method=nfs:10.10.1.10:/srv/install/fedora/12/amd64/ lang=us keymap=us ip=dhcp ksdevice=eth0 noipv6 initrd=fedora/12/amd64/initrd.img ramdisk_size=10000" >> $fedora2/fedora.menu
	echo "	text help" >> $fedora2/fedora.menu
	echo "	install fedora 12 (64-bit)" >> $fedora2/fedora.menu
	echo "	endtext" >> $fedora2/fedora.menu
	echo "label 1" >> $fedora2/fedora.menu
	echo "	menu label fedora 12 (32-bit)" >> $fedora2/fedora.menu
	echo "	kernel fedora/12/i386/vmlinuz" >> $fedora2/fedora.menu
	echo "	append method=nfs:10.10.1.10:/srv/install/fedora/12/i386/ lang=us keymap=us ip=dhcp ksdevice=eth0 noipv6 initrd=fedora/12/i386/initrd.img ramdisk_size=10000" >> $fedora2/fedora.menu
	echo "	text help" >> $fedora2/fedora.menu
	echo "	install fedora 12 (32-bit)" >> $fedora2/fedora.menu
	echo "	endtext" >> $fedora2/fedora.menu

	echo "label 2" > $xanadu2/xanadu.menu
	echo "	menu label xanadu (64-bit)" >> $xanadu2/xanadu.menu
	echo "	kernel xanadu/0.9.0/amd64/vmlinuz" >> $xanadu2/xanadu.menu
	echo "	append method=nfs:10.10.1.10:/srv/install/xanadu/0.9.0/amd64/ lang=us keymap=us ip=dhcp ksdevice=eth0 noipv6 initrd=xanadu/0.9.0/amd64/initrd.img ramdisk_size=10000" >> $xanadu2/xanadu.menu
	echo "	text help" >> $xanadu2/xanadu.menu
	echo "	install xanadu (64-bit)" >> $xanadu2/xanadu.menu
	echo "	endtext" >> $xanadu2/xanadu.menu
	echo "label 1" >> $xanadu2/xanadu.menu
	echo "	menu label xanadu (32-bit)" >> $xanadu2/xanadu.menu
	echo "	kernel xanadu/0.9.0/i386/vmlinuz" >> $xanadu2/xanadu.menu
	echo "	append method=nfs:10.10.1.10:/srv/install/xanadu/0.9.0/i386/ lang=us keymap=us ip=dhcp ksdevice=eth0 noipv6 initrd=xanadu/0.9.0/i386/initrd.img ramdisk_size=10000" >> $xanadu2/xanadu.menu
	echo "	text help" >> $xanadu2/xanadu.menu
	echo "	install xanadu (32-bit)" >> $xanadu2/xanadu.menu
	echo "	endtext" >> $xanadu2/xanadu.menu
}

function bajar () {
	if ! [[ -f "$HOME"/isos/xanadu-grub.png ]]; then
		wget -v -O "$HOME"/isos/xanadu-grub.png https://xanadulinux.files.wordpress.com/2016/03/xanadu-grub.png
	fi

	if ! [[ -f "$HOME"/isos/debian-amd64.iso ]]; then
		wget -v -O "$HOME"/isos/debian-amd64.iso http://cdimage.debian.org/debian-cd/8.3.0/amd64/iso-dvd/debian-8.3.0-amd64-DVD-1.iso
	fi
	if ! [[ -f "$HOME"/isos/debian-i386.iso ]]; then
		wget -v -O "$HOME"/isos/debian-i386.iso http://cdimage.debian.org/debian-cd/8.3.0/i386/iso-dvd/debian-8.3.0-i386-DVD-1.iso
	fi
	if ! [[ -f "$HOME"/isos/debian-i386.iso ]]; then
		wget -v -O "$HOME"/isos/debian-i386.iso http://cdimage.debian.org/debian-cd/8.3.0/i386/iso-dvd/debian-8.3.0-i386-DVD-1.iso
	fi

	if ! [[ -f "$HOME"/isos/ubuntu-amd64.iso ]]; then
		wget -v -O "$HOME"/isos/ubuntu-amd64.iso http://releases.ubuntu.com/14.04.4/ubuntu-14.04.4-desktop-amd64.iso
	fi
	if ! [[ -f "$HOME"/isos/ubuntu-i386.iso ]]; then
		wget -v -O "$HOME"/isos/ubuntu-i386.iso http://releases.ubuntu.com/14.04.4/ubuntu-14.04.4-desktop-i386.iso
	fi

	if ! [[ -f "$HOME"/isos/fedora-amd64.iso ]]; then
		wget -v -O "$HOME"/isos/fedora-amd64.iso https://download.fedoraproject.org/pub/fedora/linux/releases/23/Workstation/x86_64/iso/Fedora-Live-Workstation-x86_64-23-10.iso
	fi
	if ! [[ -f "$HOME"/isos/fedora-i686.iso ]]; then
		wget -v -O "$HOME"/isos/fedora-i686.iso https://download.fedoraproject.org/pub/fedora/linux/releases/23/Workstation/i386/iso/Fedora-Live-Workstation-i686-23-10.iso
	fi

	if ! [[ -f "$HOME"/isos/xanadu-amd64.iso ]]; then
		wget -v -O "$HOME"/isos/xanadu-amd64.iso http://xanadu.viserproject.com/descarga/xanadu-linux-0.9.0-amd64.iso
	fi
	if ! [[ -f "$HOME"/isos/xanadu-386.iso ]]; then
		wget -v -O "$HOME"/isos/xanadu-i386.iso http://xanadu.viserproject.com/descarga/xanadu-linux-0.9.0-i386-nopae.iso
	fi
}

function montar () {
	mount -o loop -t iso9660 "$HOME"/isos/debian-amd64.iso /mnt/loop
	cp /mnt/loop/install.amd/vmlinuz $debian1/amd64
	cp /mnt/loop/install.amd/initrd.gz $debian1/amd64
	cp -R /mnt/loop/* $debian4
	cp -R /mnt/loop/.disk $debian4
	umount /mnt/loop

	mount -o loop -t iso9660 "$HOME"/isos/debian-i386.iso /mnt/loop
	cp /mnt/loop/install.386/vmlinuz $debian1/i386
	cp /mnt/loop/install.386/initrd.gz $debian1/i386
	cp -R /mnt/loop/* $debian3
	cp -R /mnt/loop/.disk $debian3
	umount /mnt/loop

	mount -o loop -t iso9660 "$HOME"/isos/ubuntu-amd64.iso /mnt/loop
	cp /mnt/loop/casper/vmlinuz.efi $ubuntu1/amd64
	cp /mnt/loop/casper/initrd.lz $ubuntu1/amd64
	cp -R /mnt/loop/* $ubuntu4
	cp -R /mnt/loop/.disk $ubuntu4
	umount /mnt/loop

	mount -o loop -t iso9660 "$HOME"/isos/ubuntu-i386.iso /mnt/loop
	cp /mnt/loop/casper/vmlinuz.efi $ubuntu1/i386
	cp /mnt/loop/casper/initrd.lz $ubuntu1/i386
	cp -R /mnt/loop/* $ubuntu3
	cp -R /mnt/loop/.disk $ubuntu3
	umount /mnt/loop

	mount -o loop -t iso9660 "$HOME"/isos/xanadu-amd64.iso /mnt/loop
	cp /mnt/loop/live/vmlinuz $xanadu1/amd64
	cp /mnt/loop/live/initrd.img $xanadu1/amd64
	cp -R /mnt/loop/* $xanadu4
	cp -R /mnt/loop/.disk $xanadu4
	umount /mnt/loop

	mount -o loop -t iso9660 "$HOME"/isos/xanadu-i386.iso /mnt/loop
	cp /mnt/loop/live/vmlinuz $xanadu1/i386
	cp /mnt/loop/live/initrd.img $xanadu1/i386
	cp -R /mnt/loop/* $xanadu3
	cp -R /mnt/loop/.disk $xanadu3
	umount /mnt/loop

	# verificar si los paquetes que se copian de la instalacion de syslinux estan alli originalmente
	# actualizar los comandos de inicio en syslinux desde los respectivos iso

#debian
#ubuntu
#fedora
#xanadu

}

directorios
limpieza
iptables_clean
bajar
instalar
primeros
menu
bajar
montar

echo "Finalizado, se recomienda reiniciar."
touch /root/.listo
rm -f /run/$(basename $0).pid
exit 0
